apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-prod
namePrefix: prod-

resources:
- ../../base

#components:
#  - ../../variants/prod
#  - ../../variants/asia

patchesStrategicMerge:
- replicas.yaml
- version.yaml